# Generated by Django 5.0.6 on 2024-10-24 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0005_delete_material'),
        ('producao', '0005_alter_ordemproducao_quantidade_produzida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade_estoque', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.unidademedida')),
            ],
            options={
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='ProdutoAcabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveBigIntegerField(default=0)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('localizacao', models.CharField(max_length=100)),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.ordemproducao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.produto')),
            ],
        ),
    ]
