# Generated by Django 5.0.6 on 2024-10-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_material_estoque_minimo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoacabado',
            options={'verbose_name_plural': 'Produtos Acabados'},
        ),
        migrations.RemoveField(
            model_name='produtoacabado',
            name='ordem_producao',
        ),
    ]
