# Generated by Django 5.1.1 on 2024-10-26 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_delete_material'),
        ('estoque', '0003_alter_produtoacabado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoacabado',
            name='localizacao',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='MovimentoEstoqueAcabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('quantidade_movimentada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_mov', models.DateTimeField(auto_now_add=True)),
                ('endereco', models.CharField(max_length=20)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.funcionario')),
                ('produto_acabado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produtoacabado')),
            ],
            options={
                'verbose_name_plural': 'Movimentações PA',
            },
        ),
    ]
