# Generated by Django 5.1.1 on 2024-10-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produtoacabado_localizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoestoqueacabado',
            name='quantidade_movimentada',
            field=models.IntegerField(max_length=10),
        ),
    ]
