# Generated by Django 5.1.1 on 2024-11-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_movimentoestoqueacabado_quantidade_movimentada'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoacabado',
            name='cartucho',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtoacabado',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='produtoacabado',
            name='codigo_barra_pct',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='produtoacabado',
            name='peso_brt_caixa',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produtoacabado',
            name='peso_liq_caixa',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produtoacabado',
            name='qtd_total_caixa',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
