# Generated by Django 5.1.1 on 2025-01-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_drive_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoacabado',
            name='data_fabricacao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='produtoacabado',
            name='lote',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
