# Generated by Django 5.1.1 on 2025-01-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_produtoacabado_data_fabricacao_produtoacabado_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoacabado',
            name='peso_brt_caixa',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='produtoacabado',
            name='peso_liq_caixa',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
