# Generated by Django 5.1.1 on 2025-01-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_alter_produtoacabado_peso_brt_caixa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoestoqueacabado',
            name='endereco',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='produtoacabado',
            name='localizacao',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
