# Generated by Django 5.1.1 on 2025-02-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_alter_movimentoestoqueacabado_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='tipo',
            field=models.CharField(choices=[('acabado', 'Acabado'), ('intermediario', 'Intermediario')], default='acabado', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtoacabado',
            name='tipo',
            field=models.CharField(choices=[('acabado', 'Acabado'), ('intermediario', 'Intermediario')], default='acabado', max_length=15),
            preserve_default=False,
        ),
    ]
