# Generated by Django 5.1.1 on 2024-10-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='ativo',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=7),
        ),
    ]
