# Generated by Django 5.1.1 on 2024-09-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=100)),
                ('matricula_funcionario', models.CharField(max_length=5)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Materiais'},
        ),
    ]
