# Generated by Django 5.1.1 on 2024-09-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_funcionario_alter_material_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='nome_maquina',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='maquina',
            name='observacao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
