# Generated by Django 5.0.6 on 2024-10-17 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_cliente_alter_funcionario_matricula_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente'),
            preserve_default=False,
        ),
    ]
