# Generated by Django 5.0.6 on 2024-10-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_produto_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
