# Generated by Django 5.1.1 on 2024-11-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_remove_produto_capacidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cartucho',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='qtd_total_caixa',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
