# Generated by Django 5.1.1 on 2024-11-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_produto_cartucho_produto_qtd_total_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='material',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
