# Generated by Django 5.1.1 on 2024-11-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_alter_produto_descricao_alter_produto_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
