# Generated by Django 5.1.1 on 2025-01-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_remove_produto_cartucho_remove_produto_codigo_barra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=7),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
