# Generated by Django 5.1.1 on 2025-01-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_alter_produto_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=7, null=True),
        ),
    ]
