# Generated by Django 5.1.1 on 2025-01-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_alter_produto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
