# Generated by Django 5.1.1 on 2025-01-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_alter_produto_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nome',
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('TAMPA', 'Tampa'), ('COPO', 'Copo'), ('POTE', 'Pote'), ('BANDEJA', 'Bandeja'), ('PRATO', 'Prato'), ('KIT POTE', 'Kit Pote')], max_length=10, null=True),
        ),
    ]
