# Generated by Django 5.1.1 on 2025-01-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_remove_produto_nome_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
