# Generated by Django 5.1.1 on 2024-10-01 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('capacidade_producao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('em_manutencao', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=7)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('quantidade_apontada', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='pendente', max_length=12)),
                ('data_previsao', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ApontamentoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produzida', models.IntegerField(blank=True, null=True)),
                ('inicio_producao', models.DateTimeField()),
                ('fim_producao', models.DateTimeField(blank=True, null=True)),
                ('data_input_apontamento', models.DateTimeField(auto_now_add=True)),
                ('funcionario_apontamento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.funcionario')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.maquina')),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.ordemproducao')),
            ],
            options={
                'verbose_name_plural': 'Apontamentos',
            },
        ),
    ]
