# Generated by Django 5.1.1 on 2024-09-20 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_previsao', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_producao', 'Em Produção'), ('finalizada', 'Finalizada')], default='pendente', max_length=20)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ApontamentoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produzida', models.IntegerField()),
                ('tempo_producao', models.DurationField()),
                ('data_apontamento', models.DateTimeField()),
                ('data_input_apontamento', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.maquina')),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.ordemproducao')),
            ],
        ),
    ]
