# Generated by Django 5.1.1 on 2024-09-20 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_funcionario_alter_material_options'),
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apontamentoproducao',
            options={'verbose_name_plural': 'Apontamentos'},
        ),
        migrations.AlterModelOptions(
            name='ordemproducao',
            options={'verbose_name_plural': 'Ordens de Produção'},
        ),
        migrations.AddField(
            model_name='apontamentoproducao',
            name='funcionario_apontamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.funcionario'),
        ),
    ]
