# Generated by Django 5.1.1 on 2024-09-20 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_alter_apontamentoproducao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apontamentoproducao',
            name='data_apontamento',
        ),
        migrations.RemoveField(
            model_name='apontamentoproducao',
            name='tempo_producao',
        ),
        migrations.AddField(
            model_name='apontamentoproducao',
            name='fim_producao',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apontamentoproducao',
            name='inicio_producao',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
