# Generated by Django 5.1.1 on 2024-09-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_remove_apontamentoproducao_data_apontamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemproducao',
            options={'verbose_name_plural': 'ordens_de_producao'},
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='data_previsao',
            field=models.DateField(),
        ),
    ]
