# Generated by Django 5.0.6 on 2024-10-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0004_ordemproducao_quantidade_produzida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemproducao',
            name='quantidade_produzida',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='saldo_op',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
