# Generated by Django 5.1.1 on 2025-01-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0006_ordemproducao_is_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='data_fabricacao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='lote',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
