# Generated by Django 5.1.1 on 2025-01-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0007_ordemproducao_data_fabricacao_ordemproducao_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemproducao',
            name='cliente',
        ),
    ]
